services:
  - type: web
    name: kroii-auto-center
    runtime: node
    nodeVersion: 20.18.1
    region: frankfurt
    plan: starter
    branch: main

    buildCommand: npm install --include=dev && npm run build

    startCommand: node .next/standalone/server.js

    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_OPTIONS
        value: --max-old-space-size=768
      - key: NEXTAUTH_SECRET
        generateValue: true
      - key: NEXTAUTH_URL
        value: https://kroii.onrender.com

    autoDeploy: true
