services:
  - type: web
    name: kroii-auto-center
    runtime: node
    nodeVersion: 20.18.1
    region: frankfurt
    plan: starter
    branch: main

    buildCommand: |
      npm install --include=dev
      npm run build
      cp -r public .next/standalone/kroi-auto-center/
      cp -r .next/static .next/standalone/kroi-auto-center/.next/

    startCommand: cd .next/standalone/kroi-auto-center && node server.js

    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_OPTIONS
        value: --max-old-space-size=768
      - key: NEXTAUTH_SECRET
        generateValue: true
      - key: NEXTAUTH_URL
        value: https://kroii.onrender.com

    autoDeploy: true
